cfereday/coder-newbie-advice

- online-resources/learn-to-code-resources.md
Added in a few more resources for the resources section to learn programming.
- Odin Project for a full free curriculum
- Codecademy for a good free introduction to many topics
- Khan Academy for Programming and Computer Science fundamentals
> [FEATURE] add more free online resources to learn programming

- online-resources/free-ebooks.md
some people prefer quality written content to watching videos sometimes, therefore I'd think it's a great idea to add a few books from authors who have kindly made their books available online.
> Create a new section for free ebooks

- online-resources/learn-to-code-resources.md
Introducing Data science section
> Add 2 more learning to code resources

- online-resources/learn-to-code-resources.md
Added some resources for C# and one for Ruby Koans as It is such a great resource for learning Ruby.
Full disclosure I work for Microsoft, but this commit is my own and nothing to do with my employer.
> Updated learn to to code

- online-resources/learn-to-code-resources.md
Resources added:
egghead.io
Frontend Masters
LinkedIn Learning
> add online resources

- online-resources/learn-to-code-resources.md
Added in the Wes Bos Web Development courses under Web Development (There are a couple of really good free ones in there).
Also added in Glitch under "Resources for many languages" - which seems like a super fun platform where you can remix other projects and try out a lot of cool things related to code.
> Add two more learning to code resources

- online-resources/free-ebooks.md
The book is packed with information. Every time I read it, I learn something new about JavaScript.
> Add JavaScript The Right Way

- online-resources/learn-to-code-resources.md
"Curated collection of useful JavaScript snippets that you can understand in 30 seconds or less." 
[30-seconds-of-code](https://github.com/30-seconds/30-seconds-of-code)
> Add 30 Seconds of Code

- online-resources/tech-tests-and-interviews.md
"A curated collection of common interview questions to help you prepare for your (JavaScript) next interview."
(30-seconds-of-interviews)[https://github.com/30-seconds/30-seconds-of-interviews]
> Add 30 seconds of interviews

- online-resources/free-ebooks.md
Contains many insights on functions in JavaScript.
> Add JavaScript Allongé

- meetups/uk/meetups.md
Please can you add Codehub Bristol. We are open to coders at all experience levels, and very welcoming to newbies. Thanks!
> Add Codehub Bristol to list of UK meetups

- online-resources/learn-to-code-resources.md
Libraries offer a free lynda.com account if you get a card and ask about the account they will set you up.
> Add Free Lynda Account info

- online-resources/free-ebooks.md
Add a few more amazing free ebooks for JS :)
> add more JavaScript books

- online-resources/free-ebooks.md
- online-resources/learn-to-code-resources.md
Add Front-End Developers Handbook and Kata Koder to resources
> Add eBook & resource

- online-resources/learn-to-code-resources.md
Well done for putting this together Charlotte. I would like to propose adding my on-line courses, which covers Ruby programming for now, with more in the pipeline. Thanks in advance
> Adding dangarland.co.uk - my ruby online courses

- online-resources/learn-to-code-resources.md
I recently found this list of free APIs which I find really useful in teaching coding, and thought would be useful for self-teachers too! Also added an article from CodeNewbie on introducing APIs to give context for learners. Awesome repo Charlotte 🙌
> Add resources on APIs

- online-resources/learn-to-code-resources.md
The resource I'm adding is a "Checklist for Getting a Job". I put this together for a friend a month ago and think others may benefit from it.
> Add online resource

- README.md
- online-resources/learn-to-code-resources.md
Added multiple web development resources, and a few non-web development resources.
Added links to the README to make accessing specific documents easier, and making it easier to see what the repository covers.
DISCLAIMER:
The Git video I linked is my own personal video, but I feel it is a strong explanation of Git for anyone just getting started with version control. You are welcome to review it and I will remove it if you feel it is not what you are looking for
> Add Web Dev Resources and README Links

- online-resources/free-ebooks.md
Added free online ebook for PHP.
(This is my first ever pull request!)
> Add PHP The Right Way ebook.

- README.md
- no-install/try-before-you-buy.md
Hi Charlotte - this isn't an exhaustive list but hopefully useful. Let me know what you think (just hope I haven't messaged up the PR!)
Jim
> Online tools and try sites

- online-resources/free-ebooks.md
- online-resources/learn-to-code-resources.md
- online-resources/podcasts.md
- online-resources/tech-tests-and-interviews.md
Some resources I refer often while learning to code.
> added some resources

- no-install/try-before-you-buy.md
Found these editors super useful for intro-ing into web dev
> Adds two free web based text editors

- meetups/uk/meetups.md
Added details and hyperlink to Brighton based Code Brunch meet up group
> Added Code Brunch

- README.md
I manually squashed these commits down into one
> docs: updates bootcamps
